name: Install Binary from GitHub Releases
description: Easily install a binary from a GitHub Release that works across repositories in Rust, Go, C++, and more.
author: sigoden <sigoden@gmail.com>
branding:
  icon: box
  color: green
inputs:
  repo:
    description: The github repo
    required: true
  tag:
    description: The release tag
    default: latest
  name:
    description: The binary name
  token:
    description: The github token
    default: ${{ github.token }}
  cache:
    description: Use cache
    default: true
runs:
  using: node20
  main: dist/index.js