name: CI

on:
  push:
  schedule:
    - cron: 0 12 1 * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - run: npm ci
    - run: npm run lint
    - run: npm run build

  test-install-argc:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install binary
      uses: ./
      with:
        repo: sigoden/argc
    - name: Test
      run: |
        argc --argc-version
      shell: bash

  test-install-argc-with-cache:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install binary
      uses: ./
      with:
        repo: sigoden/argc
        cache: true
    - name: Test
      run: |
        argc --argc-version
      shell: bash

  test-install-protoc-with-tag:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install binary
      uses: ./
      with:
        repo: nats-io/nats-server
        tag: v2.10.17
        name: nats-server
    - name: Test
      run: |
        nats-server --version
      shell: bash
